[package]
name = "mcp-edit"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
rmcp = "0.4"
serde = { version = "1", features = ["derive"] }
schemars = { version = "1", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
tempfile = "3"
