[package]
name = "llm-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ratatui = "0.29.0"
textwrap = "0.16.2"
tui-realm-stdlib = "3.0.0"
tuirealm = "3.0.1"
